name: Branch build and publish

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_AUTH_TOKEN: ${{secrets.GLOBAL_READ_PACKAGES_SECRET}}
      fugro_source_url: https://nuget.pkg.github.com/fugro/index.json
    steps:
    - name: Checkout repository and initialize for LFS
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
        source-url: ${{env.fugro_source_url}}

    - name: Bootstrap tooling
      run: dotnet tool restore

    - name: Restore (nuget packages)
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Unit Test
      run: dotnet test --configuration Release --no-build --filter 'TestCategory!=SpeedTest' --logger="trx;logfilename=TestResults.trx"
 
    - name: Reporting
      uses: dorny/test-reporter@v1
      with:
        name: 'Test results report'
        reporter: 'dotnet-trx'
        path: '**/TestResults/TestResults.trx'
        only-summary: 'true'
        max-annotations: '10'
        fail-on-error: 'true'
